#!/bin/bash
cp styles.css 27styles.tmp
sed -i 's/^/"/' 27styles.tmp
sed -i 's/$/" +/' 27styles.tmp
echo 'settings.css =' > 27styles
cat 27styles.tmp >> 27styles
echo '"";' >> 27styles

cat 10meta  20prefix  25settings  27styles  30ui  40lib  50onload  60killDefault  70postfix   > build/open-google-reader.js
cp build/open-google-reader.js build/open-google-reader.user.js

rm 27styles
rm 27styles.tmp
